NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
library(dplyr)
library(ggplot2)
a3<-group_by(NEI,year,type)
a3<-filter(a3,fips == "24510")
b3<-summarise(a3,S=sum(Emissions))
png("plot3.png",width=600,height=600,units="px")
qplot(year,S,data=b3,facets=type~.,color=type,main="Total PM2.5 Emission in Baltimore City by type",ylab="Total PM2.5 Emission",geom="path")
dev.off()