NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
library(dplyr)
a<-group_by(NEI,year)
a2<-filter(a,fips == "24510")
b2<-summarise(a2,S=sum(Emissions))
png("plot2.png",width=480,height=480,units="px")
with(b2,plot(year,S,type="l",ylab="Total PM2.5 Emissions",col="blue"))
title(main="PM2.5 Emission in Baltimore City")
dev.off()
